# Basic formatting
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Auto"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Code organization
reorder_imports = true
reorder_modules = true

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# Function formatting
fn_args_layout = "Tall"
fn_single_line = false
where_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true

# Struct and enum formatting
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Chain formatting
chain_width = 60
use_small_heuristics = "Default" 